name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{19bd3943-ef3d-46bb-8718-e233e27cc67a}}
          heroku_app_name: "titan-sports-simulator" #Must be unique in Heroku
          heroku_email: "juliesenynam@gmail.com"
